target-version = "py312"

[lint]
select = [
    "E", "F", "I", "W", "UP", "B", "SIM", "C4", "N", "RUF",
    "PIE", "PYI", "ISC", "ICN", "INP001", "Q", "RSE",
    "RET", "SIM", "PERF", "PLC", "PLE", "PLW", "FURB",

    "PT"
]
ignore = [
    "PLW2901", # redefined-loop-name
]